'use client'

import React, { useState, useEffect } from 'react';
import { motion, useAnimation } from 'framer-motion';
import Head from 'next/head';

import {
    BsSearch,
    BsQuestionSquareFill ,
    BsBookmarkFill,
    BsFillArrowLeftSquareFill,
    BsPeopleFill,
    BsTerminalFill,
    BsFillArrowRightSquareFill,
    BsLayersFill,
    BsMapFill
} from 'react-icons/bs';
import { MdSource } from "react-icons/md";
import { FaHistory } from "react-icons/fa";
import { MdFeedback } from 'react-icons/md';
import { FaCog } from 'react-icons/fa';

import styles from './Sidebar.module.css'; // Importar estilos como módulo CSS



const Sidebar = () => {
    const [active, setActive] = useState(false);
    const controls = useAnimation();
    const controlText = useAnimation();
    const controlTitleText = useAnimation();

    const showMore = () => {
        controls.start({
            width: '168px',
            transition: { duration: 0.101 },
        });
        controlText.start({
            opacity: 1,
            display: 'block',
            transition: { delay: 0.3 },
        });
        controlTitleText.start({
            opacity: 1,
            transition: { delay: 0.3 },
        });
        setActive(true);
    };

    const showLess = () => {
        controls.start({
            width: '55px',
            transition: { duration: 0.101 },
        });

        controlText.start({
            opacity: 0,
            display: 'none',

        });

        controlTitleText.start({
            opacity: 0,
        });
        setActive(false);
    };

    const toggleSidebar = () => {
        setActive(!active);
        if (!active) {
            showMore();
        } else {
            showLess();
        }
    };

    useEffect(() => {
        showLess();
    }, []);

    
    const data = [
        {
            name: 'Discover',
            items: [
                {
                    title: 'Config',
                    icon: FaCog ,
                },
                {
                    title: 'Fuentes',
                    icon: MdSource,
                },
                {
                    title: 'Capas',
                    icon: BsLayersFill,
                },
                {
                    title: 'Ayuda',
                    icon: BsQuestionSquareFill ,
                },
                {
                    title: 'Mapas',
                    icon: BsMapFill,
                },
                {
                    title: 'Historial',
                    icon: FaHistory ,
                },
                {
                    title: 'Buscador',
                    icon: BsSearch,
                },
            ],
        },
    ];

    const datafooter = [
        {
            name: '',
            items: [
                {
                    title: 'Docs',
                    icon: BsBookmarkFill,
                },
                {
                    title: 'Changelog',
                    icon: BsTerminalFill,
                },
                {
                    title: 'Feedback',
                    icon: MdFeedback,
                },
                {
                    title: 'Invite people',
                    icon: BsPeopleFill,
                },
            ],
        },
    ];

    return (
        <div>
            {/* <Head>
                <title>Sidebar</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head> */}

            <motion.div animate={controls} className={styles.sidebar}>

                <div onClick={toggleSidebar}>
                    {active ? (
                        <BsFillArrowLeftSquareFill className={`${styles.sidebarButton} ${styles.sidebarButtonOpen}`} />
                    ) : (
                        <BsFillArrowRightSquareFill className={`${styles.sidebarButton} ${styles.sidebarButtonClosed}`} />
                    )}
                </div>


                <div className='grow'>
                    {data.map((group, index) => (
                        <div key={index} className='my-2'>
                            <motion.p animate={controlTitleText} className={styles.sidebarTitleText}>
                                {group.name}
                            </motion.p>

                            {group.items.map((item, index2) => (
                                <div key={index2} className={styles.menuButton}>
                                    <item.icon className={styles.buttonIcon} />
                                    <motion.p animate={controlText} className={styles.buttonText}>
                                        {' '}
                                        {item.title}
                                    </motion.p>
                                </div>
                            ))}
                        </div>
                    ))}
                </div>

                {/* <div>
                    {datafooter.map((group, index) => (
                        <div key={index} className='my-2'>
                            <motion.p animate={controlTitleText} className={styles.sidebarTitleText}>
                                {group.name}
                            </motion.p>

                            {group.items.map((item, index2) => (
                                <div key={index2} className='flex px-4 py-1 cursor-pointer'>
                                    <item.icon className={styles.sidebarIcon} />
                                    <motion.p animate={controlText} className={styles.sidebarText}>
                                        {' '}
                                        {item.title}
                                    </motion.p>
                                </div>
                            ))}
                        </div>
                    ))}
                </div> */}
            </motion.div>
            
        </div>
    );
};

export default Sidebar;