import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MapComponent from "./map/MapComponent";
import SidebarMenu from "./components/sidebarMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Visor de Mapas Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
      <div>
        <div></div>

        <div>{children}</div>
          <MapComponent/>
        <SidebarMenu />
      </div>
      </body>
    </html>
  );
}
